import { defineSidebar } from '../_utils'

export const algorithm = defineSidebar([
  {
    text: '排序算法',
    base: 'sorting',
    collapsed: false,
    items: [
      { text: '冒泡排序', link: 'bubble-sort' },
      { text: '选择排序', link: 'selection-sort' },
      { text: '插入排序', link: 'insertion-sort' },
      { text: '希尔排序', link: 'shell-sort' },
      { text: '归并排序', link: 'merge-sort' },
      { text: '快速排序', link: 'quick-sort' },
      { text: '堆排序', link: 'heap-sort' },
      { text: '桶排序', link: 'bucket-sort' },
      { text: '基数排序', link: 'radix-sort' },
      { text: '计数排序', link: 'counting-sort' },
      { text: '鸡尾酒排序', link: 'cocktail-shaker-sort' },
      { text: '梳排序', link: 'comb-sort' },
      { text: '煎饼排序', link: 'pancake-sort' },
      { text: '排序网络', link: 'sorting-network' },
      { text: 'Tim 排序', link: 'tim-sort' },
    ],
  },
  {
    text: '查找算法',
    base: 'searching',
    collapsed: false,
    items: [
      { text: '线性查找', link: 'linear-search' },
      { text: '二分查找', link: 'binary-search' },
      { text: '插值查找', link: 'interpolation-search' },
      { text: '跳跃查找', link: 'jump-search' },
      { text: '斐波那契查找', link: 'fibonacci-search' },
      { text: '哈希查找', link: 'hash-search' },
      { text: '深度优先搜索', link: 'depth-first-search' },
      { text: '广度优先搜索', link: 'breadth-first-search' },
      { text: '三分查找', link: 'ternary-search' },
    ],
  },
  {
    text: '图算法',
    base: 'graph',
    collapsed: false,
    items: [
      { text: 'Dijkstra', link: 'dijkstra' },
      { text: 'Bellman Ford', link: 'bellman-ford' },
      { text: 'Floyd Warshall', link: 'floyd-warshall' },
      { text: '最小生成树', link: 'minimum-spanning-tree' },
      { text: 'Kruskal', link: 'kruskal' },
      { text: 'Prim', link: 'prim' },
      { text: '拓扑排序', link: 'topological-sort' },
      { text: 'A* 搜索', link: 'a-star-search' },
      { text: '强连通分量', link: 'strongly-connected-components' },
      { text: '二分图检测', link: 'bipartite-graph-check' },
    ],
  },
  {
    text: '动态规划',
    base: 'dynamic-programming',
    collapsed: false,
    items: [
      { text: '斐波那契数列', link: 'fibonacci-sequence' },
      { text: '背包问题', link: 'knapsack-problem' },
    //   { text: '最长公共子序列', link: 'longest-common-subsequence' },
    //   { text: '最长递增子序列', link: 'longest-increasing-subsequence' },
    //   { text: '零钱兑换问题', link: 'coin-change-problem' },
    //   { text: '编辑距离', link: 'edit-distance' },
    //   { text: '矩阵链乘法', link: 'matrix-chain-multiplication' },
    //   { text: '最长回文子序列', link: 'longest-palindromic-subsequence' },
    //   { text: '切割钢条问题', link: 'rod-cutting-problem' },
    ],
  },
  //   {
  //     text: '贪心算法',
  //     base: 'greedy',
  //     collapsed: false,
  //     items: [
  //       { text: '活动选择问题', link: 'activity-selection-problem' },
  //       { text: '霍夫曼编码', link: 'huffman-coding' },
  //       { text: '最小生成树', link: 'minimum-spanning-tree' },
  //       { text: '区间调度问题', link: 'greedy-interval-scheduling' },
  //       { text: '作业调度问题', link: 'job-sequencing-problem' },
  //       { text: '分数背包问题', link: 'fractional-knapsack' },
  //     ],
  //   },
  //   {
  //     text: '分治算法',
  //     base: 'divide-and-conquer',
  //     collapsed: false,
  //     items: [
  //       { text: '归并排序', link: 'merge-sort' },
  //       { text: '快速排序', link: 'quick-sort' },
  //       { text: '最近点对问题', link: 'closest-pair-of-points' },
  //       { text: '二分查找', link: 'binary-search' },
  //     ],
  //   },
  //   {
  //     text: '回溯算法',
  //     base: 'backtracking',
  //     collapsed: false,
  //     items: [
  //       { text: '八皇后问题', link: 'n-queens-problem' },
  //       { text: '排列组合问题', link: 'permutations' },
  //       { text: '子集生成', link: 'subsets-generation' },
  //       { text: '数独求解', link: 'sudoku-solver' },
  //       { text: '单词拆分问题', link: 'word-break-problem' },
  //     ],
  //   },
  //   {
  //     text: '字符串算法',
  //     base: 'string',
  //     collapsed: false,
  //     items: [
  //       { text: 'KMP算法', link: 'kmp-algorithm' },
  //       { text: 'Boyer-Moore 算法', link: 'boyer-moore-algorithm' },
  //       { text: 'Rabin-Karp 算法', link: 'rabin-karp-algorithm' },
  //       { text: '字符串匹配', link: 'string-matching' },
  //       { text: '后缀数组', link: 'suffix-array' },
  //       { text: 'Z算法', link: 'z-algorithm' },
  //       { text: '编辑距离', link: 'edit-distance-string' },
  //     ],
  //   },
  //   {
  //     text: '数学算法',
  //     base: 'mathematics',
  //     collapsed: false,
  //     items: [
  //       { text: '埃拉托斯特尼筛法', link: 'sieve-of-eratosthenes' },
  //       { text: '欧几里得算法', link: 'euclidean-algorithm' },
  //       { text: '快速幂算法', link: 'fast-exponentiation' },
  //       { text: '模逆元素', link: 'modular-multiplicative-inverse' },
  //       { text: '矩阵快速幂', link: 'matrix-exponentiation' },
  //       { text: '线性方程组求解', link: 'linear-equation-solver' },
  //     ],
  //   },
  //   {
  //     text: '并查集算法',
  //     base: 'disjoint-set',
  //     collapsed: false,
  //     items: [
  //       { text: '并查集', link: 'disjoint-set' },
  //       { text: '并查集应用', link: 'union-find-algorithm' },
  //       { text: 'Kruska 算法中的并查集', link: 'kruskal-algorithm-disjoint-set' },
  //     ],
  //   },
//   {
//     text: '网络流算法',
//     base: 'network-flow',
//     collapsed: false,
//     items: [
//       { text: '最大流算法', link: 'maximum-flow' },
//       { text: '最小割问题', link: 'minimum-cut' },
//       { text: 'Edmonds-Karp 算法', link: 'edmonds-karp-algorithm' },
//       { text: 'Dinic 算法', link: 'dinic-algorithm' },
//       { text: 'Ford-Fulkerson算法', link: 'ford-fulkerson-algorithm' },
//     ],
//   },
//   {
//     text: '其他算法',
//     base: 'other',
//     collapsed: false,
//     items: [
//       { text: '排列组合问题', link: 'permutations-combinations' },
//       { text: '寻找第 k 大元素', link: 'find-kth-largest' },
//       { text: '线性规划', link: 'linear-programming' },
//       { text: '蒙特卡洛算法', link: 'monte-carlo-algorithm' },
//       { text: '随机化算法', link: 'randomized-algorithm' },
//     ],
//   },
],
)
